version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
